uploads = []
generated = []

[[outputs]]
id = "HDiEagv4MzO-iaf8tzOc5"
uri = "file://documents/Source_of_Wealth_Process_Document.docx"
type = "word_document"
title = "Source of Wealth — Due Diligence Process Document"

[[outputs]]
id = "_J1d_ArgnKIvkai34xgFx"
uri = "file://artifacts/sow-overview-video/public/audio/bg_music.mp3"
type = "audio"
title = "background music"
