// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prospecting-journey/GuidedJourney.tsx": () => import("../components/mockups/prospecting-journey/GuidedJourney.tsx"),
  "./components/mockups/prospecting-journey/PipelineBoard.tsx": () => import("../components/mockups/prospecting-journey/PipelineBoard.tsx")
};
